name: Time-based Push Restriction

on:
  push:
    branches:
      - main # or any other branch you want to protect

jobs:
  check_time:
    runs-on: ubuntu-latest
    steps:
    - name: Check if push is allowed at this time
      run: |
        CURRENT_HOUR=$(date +'%H')
        if [[ $CURRENT_HOUR -ge 9 && $CURRENT_HOUR -le 22 ]]; then
          echo "Push is not allowed between 09:00 and 22:00"
          exit 1
        fi
